language: php
php:
  - '7.2'
script:
- echo "skipping tests"

before_install:
- openssl aes-256-cbc -K $encrypted_210da2545c7c_key -iv $encrypted_210da2545c7c_iv
  -in rackdeploy-e4100ec9a353.json.enc -out rackdeploy-e4100ec9a353.json -d

deploy:
  provider: gae
  keyfile: "rackdeploy-e4100ec9a353.json"
  project: rackdeploy